# usage:
# ansible-playbook 1.yml --extra-vars "host=test ip=1.1.1.1"
# host: Nagios host
# ip: IP address of monitoring machine

#/usr/local/nagios/etc/hosts
#ESXi host WITCHDOCTOR.cfg

#define host {
#    host_name                ESXi host PALADIN
#    use                      xiwizard_generic_host
#    address                  paladin.corp.mutualink.net
#    max_check_attempts       5
#    check_interval           5
#    retry_interval           1
#    check_period             xi_timeperiod_24x7
#    contacts                 IT Alerts
#    notification_interval    60
#    notification_period      xi_timeperiod_24x7
#    icon_image               vmware.png
#    statusmap_image          vmware.png
#    _xiwizard                vmware
#    register                 1
#}




---
- name: Add to Nagios
  hosts: 192.168.2.18
  vars:
    hostgroup: ""
    host: ""
    ip: ""
  become: true

  tasks:
    - name: "Copy Linux hosts config file"
      command: cp /usr/local/nagios/etc/hosts/ESXi host WITCHDOCTOR.cfg /usr/local/nagios/etc/objects/{{ host }}.cfg

    - name: "Replace host - Linux"
      replace:
        path: /usr/local/nagios/etc/objects/{{ host }}.cfg
        regexp: "ESXi host PALADIN"
        replace: "{{ host }}"

    - name: "Replace IP - Linux"
      replace:
        path: /usr/local/nagios/etc/objects/{{ host }}.cfg
        regexp: "paladin.corp.mutualink.net"
        replace: "{{ ip }}"

    - name: "Restart nagios"
      service:
        name: nagios
        state: restarted
